package org.example.DSMSModule;


/**
* DSMSModule/DSMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org/example/DSMS_CORBA.idl
* Monday, February 24, 2025 4:01:57 PM EST
*/

public interface DSMS extends DSMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DSMS
