package org.example.DSMSModule;


/**
* DSMSModule/DSMSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from org/example/DSMS_CORBA.idl
* Monday, February 24, 2025 4:01:57 PM EST
*/

public abstract class DSMSPOA extends org.omg.PortableServer.Servant
 implements DSMSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addShare", new java.lang.Integer (0));
    _methods.put ("removeShare", new java.lang.Integer (1));
    _methods.put ("listShareAvailability", new java.lang.Integer (2));
    _methods.put ("purchaseShare", new java.lang.Integer (3));
    _methods.put ("getShares", new java.lang.Integer (4));
    _methods.put ("sellShare", new java.lang.Integer (5));
    _methods.put ("swapShares", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Admin roles
       case 0:  // DSMSModule/DSMS/addShare
       {
         String shareID = in.read_string ();
         String shareType = in.read_string ();
         int capacity = in.read_long ();
         String $result = null;
         $result = this.addShare (shareID, shareType, capacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DSMSModule/DSMS/removeShare
       {
         String shareID = in.read_string ();
         String shareType = in.read_string ();
         String $result = null;
         $result = this.removeShare (shareID, shareType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DSMSModule/DSMS/listShareAvailability
       {
         String shareType = in.read_string ();
         String $result = null;
         $result = this.listShareAvailability (shareType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // Buyer roles
       case 3:  // DSMSModule/DSMS/purchaseShare
       {
         String buyerID = in.read_string ();
         String shareID = in.read_string ();
         String shareType = in.read_string ();
         int shareCount = in.read_long ();
         String $result = null;
         $result = this.purchaseShare (buyerID, shareID, shareType, shareCount);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DSMSModule/DSMS/getShares
       {
         String buyerID = in.read_string ();
         String $result = null;
         $result = this.getShares (buyerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DSMSModule/DSMS/sellShare
       {
         String buyerID = in.read_string ();
         String shareID = in.read_string ();
         int shareCount = in.read_long ();
         String $result = null;
         $result = this.sellShare (buyerID, shareID, shareCount);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // DSMSModule/DSMS/swapShares
       {
         String buyerID = in.read_string ();
         String oldShareID = in.read_string ();
         String oldShareType = in.read_string ();
         String newShareID = in.read_string ();
         String newShareType = in.read_string ();
         String $result = null;
         $result = this.swapShares (buyerID, oldShareID, oldShareType, newShareID, newShareType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DSMSModule/DSMS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DSMS _this() 
  {
    return DSMSHelper.narrow(
    super._this_object());
  }

  public DSMS _this(org.omg.CORBA.ORB orb) 
  {
    return DSMSHelper.narrow(
    super._this_object(orb));
  }


} // class DSMSPOA
